apiVersion: 1

datasources:
  # Loki - Logs
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'

  # Tempo - Traces
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: false
    uid: tempo
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['request_id', 'trace_id']
        mappedTags: [{ key: 'service', value: 'service' }]
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service', value: 'service' }]
        queries:
          - name: 'Request rate'
            query: 'sum(rate(http_requests_total{$$__tags}[5m]))'
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki

  # Prometheus - Metrics
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    uid: prometheus
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: 'View trace'
      prometheusType: Prometheus
      prometheusVersion: 2.51.0
