icao = {
"SWA":"Southwest Airlines",
"AAL":"American Airlines",
"DAL":"Delta Air Lines",
"UAL":"United Airlines",
"SKW":"SkyWest Airlines",
"JBU":"JetBlue Airways",
"RPA":"Republic Airways",
"UPS":"UPS Airlines",
"NKS":"Spirit Airlines",
"ENY":"Envoy Air (American Eagle)",
"FFT":"Frontier Airlines",
"ASA":"Alaska Airlines",
"EDV":"Endeavor Air (Delta Connection)",
"EJA":"NetJets (Private)",
"JIA":"PSA Airlines (American Eagle)",
"FDX":"FedEx Express",
"AAY":"Allegiant Air",
"ACA":"Air Canada",
"PDT":"Piedmont Airlines (American Eagle)",
"ASH":"Mesa Airlines",
"UCA":"CommutAir (United Express)",
"WJA":"WestJet",
"LXJ":"Flexjet (Private)",
"QXE":"Horizon Air",
"GJS":"GoJet Airlines (United Express)",
"CXK":"Sun Country Airlines",
"MXY":"Breeze Airways",
"JZA":"Jazz Aviation (Air Canada Express)",
}