server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{compose_service=~".*backend.*|.*celery.*|.*nginx.*|.*frontend.*"}'
          stages:
            - json:
                expressions:
                  level: levelname
                  logger: name
                  msg: message
                  service: service
                  request_id: request_id
                  http_method: http_method
                  http_path: http_path
                  status_code: status_code
                  latency_ms: latency_ms
            - labels:
                level:
                logger:
                service:
                compose_service:
                compose_project:
